language: python
python:
  - "3.6"
install:
  - pip install -c constraints.txt -e .
  - pip install -c constraints.txt -r requirements.txt
script:
  - flake8
  - mypy --ignore-missing-imports ethindex
#  - coverage run --source=ethindex -m py.test tests
#after_success:
#  - coverage report
branches:
  only:
  - master
  - develop
